version: '3.8'

services:
  #reverse Proxy 관련 파트
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - backend
      - frontend

  # Certbot(SSL 인증서)
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "certbot certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email --staging -d goodnight123.site -d www.goodnight123.site"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
       database :
         condition: service_healthy  # db 실행후에 실행

    # React
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"


  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: board
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL" ,"pg_isready -U postgres -d board"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
   postgres_data:


